spring:
  mail:
    host: smtp.qq.com
    username: 56093273@qq.com
    password: tljbvojjskilbhdc
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
            required: true
my:
  project:
    name: admin
  master-db:
    config:
      db: erp
      url: 10.3.23.191
      username: root
      password: Root@1234
      driver: com.mysql.cj.jdbc.Driver

swagger: # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping:
app:
  projectId: mini
  moduleId: ${spring.application.name}
  log:
    path: /data/log

mqtt:
  host: tcp://49.232.132.116:1883
  user-name: sharp
  password: Adm!n123
  client:
    id: sharp-server

server:
  port: 8000
