
# 开发环境配置
server: # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet: # 应用的访问路径
    context-path: /
  tomcat: # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads: # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
# 日志配置
logging:
  config: classpath:logback-boot.xml
  level:
    com.bidr: trace
    org.springframework: warn
bidr:
  result:
    class-white-list:
      - springfox.documentation.swagger.web.ApiResourceController
      - springfox.documentation.oas.web.OpenApiControllerWebMvc
  # 用户配置
user:
  password: # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10
# Spring配置
spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  # 资源信息
  messages: # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart: # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart: # 热部署开关
      enabled: true
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    druid:
#      statViewServlet:
#        enabled: true
#        # 设置白名单，不填则允许所有访问
#        allow:
#        url-pattern: /druid/*
#        # 控制台管理用户名和密码
#        login-username: ruoyi
#        login-password: 123456
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driverClassName: ${my.master-db.config.driver}
          url: jdbc:${my.master-db.config.type}://${my.master-db.config.url}:${my.master-db.config.port}/${my.master-db.config.db}?${my.master-db.config.property}
          username: ${my.master-db.config.username}
          password: ${my.master-db.config.password}
        # 从库数据源
        slave:
          lazy: true
          driverClassName: ${my.slave-db.config.driver}
          url: jdbc:${my.slave-db.config.type}://${my.slave-db.config.url}:${my.slave-db.config.port}/${my.slave-db.config.db}?${my.slave-db.config.property}
          username: ${my.slave-db.config.username}
          password: ${my.slave-db.config.password}
  # redis 配置
  redis: # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool: # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

management:
  info:
    git:
      mode: full

# token配置
token: # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis: # 搜索指定包别名
  # typeAliasesPackage: com.tms.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  # mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger: # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss: # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

my:
  cache:
    expired: 10
  rest:
    proxy:
      enable: false
      host:
      port:
    config:
      request:
        timeout: 5000
      connect:
        timeout: 5000
      read:
        timeout: 30000
  project:
    name: sharp
