server:
  port: 8080

  # db configurations
my:
  master-db:
    config:
      username: root
      password:
      driver: com.mysql.cj.jdbc.Driver
      type: mysql
      url: localhost
      port: 3306
      property: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  slave-db:
    config:
      username: root
      password:
      driver: com.mysql.cj.jdbc.Driver
      type: mysql
      url: localhost
      port: 3306
      property: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8

spring:
  redis:
    host: localhost
    port: 6379
