server:
  port: 8080

  # db configurations
my:
  master-db:
    config:
      username: root
      password:
      driver: com.mysql.cj.jdbc.Driver
      type: mysql
      url: localhost
      port: 3306
      property: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  slave-db:
    config:
      db:
      username: root
      password:
      driver: com.mysql.cj.jdbc.Driver
      type: mysql
      url: localhost
      port: 3306
      property: useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8

spring:
  datasource:
    dynamic:
      hikari:
        connection-timeout: 60000
        validation-timeout: 3000
        idle-timeout: 60000
        login-timeout: 5
        max-lifetime: 30000
        maximum-pool-size: 10
        minimum-idle: 10
  redis:
    host: localhost
    port: 6379
